# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Maria/facultate/SSC/proiect/Signals_filter/Signals_filter.cache/wt [current_project]
set_property parent.project_path D:/Maria/facultate/SSC/proiect/Signals_filter/Signals_filter.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo d:/Maria/facultate/SSC/proiect/Signals_filter/Signals_filter.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/Maria/facultate/SSC/proiect/Signals_filter/Signals_filter.srcs/sources_1/new/multiplier.vhd
  D:/Maria/facultate/SSC/proiect/Signals_filter/Signals_filter.srcs/sources_1/new/adder.vhd
  D:/Maria/facultate/SSC/proiect/Signals_filter/Signals_filter.srcs/sources_1/new/ssd.vhd
  D:/Maria/facultate/SSC/proiect/Signals_filter/Signals_filter.srcs/sources_1/new/mpg.vhd
  D:/Maria/facultate/SSC/proiect/Signals_filter/Signals_filter.srcs/sources_1/new/filter.vhd
  D:/Maria/facultate/SSC/proiect/Signals_filter/Signals_filter.srcs/sources_1/new/display.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Maria/facultate/SSC/proiect/Signals_filter/Signals_filter.srcs/constrs_1/imports/proiect/constraints.xdc
set_property used_in_implementation false [get_files D:/Maria/facultate/SSC/proiect/Signals_filter/Signals_filter.srcs/constrs_1/imports/proiect/constraints.xdc]


synth_design -top display -part xc7a35tcpg236-1


write_checkpoint -force -noxdef display.dcp

catch { report_utilization -file display_utilization_synth.rpt -pb display_utilization_synth.pb }
